### ISSUE TITLE
Why i'm getting `TypeError: 'module' object is not callable`?

### ISSUE THREAD

**Issue by yzdann** [linkedin/shiv#137]
This is my `main.py`.
```py
.
.
.

try:
    cmd_type = sys.argv[1]

except IndexError:
    cmd_type = "run"

if cmd_type == "manage":
    call_command(*sys.argv[2:])

elif cmd_type == "run":
    call_command("runserver")

.
.
.
```

Here i ran command to see my migrations for django app built by shiv even this command exited successfully but with that `TypeError` i cannot use exit code of command. what am i missing? or what can i do to handle that?
```console
shiv on  shiv [$?] via shiv
[I] ➜ ./myapp-1.6.3-3a380acb.pyz manage showmigrations auth
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./myapp-1.6.3-3a380acb.pyz/__main__.py", line 3, in <module>
  File "./myapp-1.6.3-3a380acb.pyz/_bootstrap/__init__.py", line 179, in bootstrap
  File "./myapp-1.6.3-3a380acb.pyz/_bootstrap/__init__.py", line 33, in run
TypeError: 'module' object is not callable

shiv on  shiv [$?] via shiv
[I] ➜ echo $?
1
```

**Comment by yzdann** [comment]
i append
```py
    sys.exit()
```
to `main.py` this makes zipapp to cleanly exit but i think it's not a good practice but for now i will go with this.

**Comment by lorencarvalho** [comment]
Hi @yzdann, 

So, this exception is being thrown from [here](https://github.com/linkedin/shiv/blob/master/src/shiv/bootstrap/__init__.py#L33), which typically means that whatever import string you provided is not importing a _callable_, but rather an entire module. Can you show me how you are creating the pyz? (The output from the `shiv-info` command would be helpful too)

I also notice you have a function named `call_command`, does this happen to do any sort of subprocess call? If you are invoking any sort of _python_ script in a subprocess call, it's important to build the pyz with the `-E` or `--extend-pythonpath` command, so that any subprocess calls inherit the parent process's PYTHONPATH variable.

**Comment by yzdann** [comment]
Thank you for your(@lorencarvalho ) attention.

Here is my `build.sh`. I also added `-E` but still i'm getting the same error for `call_command`.
```sh
#!/usr/bin/bash
HEAD_SHA=$(git rev-parse HEAD | head -c 8)
APP_VERSION=$(egrep VERSION myapp/settings/base.py | egrep -o "[[:digit:]][.[:digit:]]*")
DIST_SETTINGS_PATH="dist/myapp/settings/"
PYTHON="python3"

usage(){
  echo "Usage: $0"
  echo "  -p : python you want to use"
  echo "  -c : client name you want to use"
}

while getopts "c:p:" opt; do
  case "$opt" in
  \?) usage && exit 0;;
  : ) echo "Invalid option: $OPTARG requires an argument" 1>&2;;
  p) PYTHON="${OPTARG}";;
  esac
done

BUILD_NAME="myapp-${APP_VERSION}-${HEAD_SHA}.pyz"
PYTHON_VERSION=$($PYTHON --version | egrep -io "Python\s[[:digit:]]*[.[:digit:]]*")
echo "$(tput setaf 2) Building with $PYTHON_VERSION $(tput sgr0)"
# clean old build
rm -r dist $BUILD_NAME 2>/dev/null && echo "$(tput setaf 1) Removing old build: $BUILD_NAME and dist $(tput sgr0)"

# include the dependencies from requirements.txt
$PYTHON -m pip install -r requirements/requirements.txt --target dist/

# specify which files to be included in the build
# You probably want to specify what goes here
cp -r \
-t dist \
myapp auth pay config manage.py

# remove .env and create fake one to use within settings.base that we import this to settings.production
rm $DIST_SETTINGS_PATH/.env
cp $DIST_SETTINGS_PATH/env.example $DIST_SETTINGS_PATH/.env


# finally, build!
shiv --site-packages dist --compressed -E -p "/usr/bin/env $PYTHON" -o $BUILD_NAME -e myapp.main

```

```console
node-3 on  shiv [$!?] 
[I] ➜ shiv-info myapp-1.6.3-b1d335b7.pyz -j
{
    "always_write_cache": false,
    "build_id": "d725d1099b74372ec07b1692cee7e84b967c828fbc2600ac702df91f9f89d965",
    "built_at": "2020-03-10 20:23:40",
    "compile_pyc": false,
    "entry_point": "SecurityAdvisoryNode.main",
    "extend_pythonpath": true,
    "script": null,
    "shiv_version": "0.1.1"
}
```

**Comment by lorencarvalho** [comment]
Hi @yzdann, thanks this is helpful.

I think the crux of your issue is on the last line of your `build.sh` script, where you invoke `shiv`:
```
shiv --site-packages dist --compressed -E -p "/usr/bin/env $PYTHON" -o $BUILD_NAME -e myapp.main
```
The string you pass to `-e` must be _callable_, and the snippet you show of `main.py` indicates it's a script, e.g. something you would run like `python3 ./myapp/main.py`. If your application defines any `console_script` ([doc](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point)) entries you can use the `-c` argument.
 
All you need to do is sequester the runnable logic in `main.py` into a function. So, if your script is:
```main.py
try:
    cmd_type = sys.argv[1]
except IndexError:
    cmd_type = "run"
if cmd_type == "manage":
    call_command(*sys.argv[2:])
elif cmd_type == "run":
    call_command("runserver")
```

Change it to:
```main.py
def cli():
    try:
        cmd_type = sys.argv[1]
    except IndexError:
        cmd_type = "run"
    if cmd_type == "manage":
        call_command(*sys.argv[2:])
    elif cmd_type == "run":
        call_command("runserver")

if __name__ == "__main__":
    cli()
```

And then change the string you pass to `-e` to be `myapp.main:cli`.

Let me know if that helps!

**Comment by yzdann** [comment]
Hi @lorencarvalho.
Thank you some much for your time.
You're right i dumbly think that `main.py` name will do some magic so i don't need to define `__name__== "__main__"`.
I changed that to `myapp.main:cli` and that fixed the problem.

**Comment by flutterq** [comment]
[All possible working solution at [Solved] TypeError: ‘module’ object is not callable
](https://flutterq.com/typeerror-module-object-is-not-callable/)
