### ISSUE TITLE
document similarities/differences with pantsbuild/pex

### ISSUE THREAD

**Issue by anthrotype** [linkedin/shiv#14]
hello,
I just discovered this very cool project. At first sight, this looks very similar to https://github.com/pantsbuild/pex. For casual users passing by, it would be nice if the README contained a brief paragraph with the similarities and differences between the two projects.
Thank you.

**Comment by sixninetynine** [comment]
Hi @anthrotype ! Good eye, `shiv` is actually largely inspired by pex, which is a fantastic piece of software.

I'll expand on this bit of history as part of the doc overhaul requested in #10, but long story short is that we built `shiv` to address the invocation overhead that pex imposes.

Because pex leans heavily on `pkg_resources`, it's subject to substantial slowdown due to https://github.com/pypa/setuptools/issues/510. Pex actually somewhat exacerbates the slowness by adding each dependency to sys.path individually. 

So you can think of `shiv` as a reimagining of pex without pkg_resources :)
