### ISSUE TITLE
Option to remove "-E" switch from shebang line

### ISSUE THREAD

**Issue by grantjenks** [linkedin/shiv#177]
I have a scenario where I'm wanting to deploy a shiv package to a Spark cluster. The Spark cluster already has pyspark installed and before launching Python does a lot to setup the environment, which includes setting the PYTHONPATH. Unfortunately, the shiv package shebang line passes "-E" to Python which tells the interpreter to disregard the PYTHONPATH environment variable.

Is it reasonable to add a shiv switch to remove the "-E" option from the shebang line? I'm thinking of "--no-ignore-python-path" or "--regard-python-path" as a switch name.

Also curious if a package could be excluded from the zipapp. For the scenario above, it would be helpful if a "--exclude pyspark" option were supported. Exclusions would be akin to running `zip -d ./example.pyz 'site-packages/pyspark/*'` after packaging. I think this could be useful for other heavyweight packages like tensorflow and pytorch.

**Comment by lorencarvalho** [comment]
Hi @grantjenks,

`shiv` itself has no opinion about the shebang you supply, if omitted, we try to guess the right shebang using [this function](https://github.com/linkedin/shiv/blob/main/src/shiv/cli.py#L69-L99). Personally, I would like to remove that function and just default to `/usr/bin/env python3`, but I haven't made that change yet.

I think the issue you are facing is that the plugin you are using to create PYZ is supplying it's own shebang and passing it to `shiv` via:
```
  -p, --python TEXT              The python interpreter to set as the shebang
                                 (such as '/usr/bin/env python3')
```

As far as excluding packages, what I typical like to recommend is that if a user needs to exclude some packages or otherwise modify the dependency set that the pyz ships with, they can simply prepare their own site-packages directory and pass it to `shiv` via `--site-packages` instead of relying on shiv delegating commands to pip. Something like:
```
$ pip install package_a package_b --target ./my/local/path
$ shiv -o outfile --site-packages ./my/local/path
```

**Comment by grantjenks** [comment]
Thanks @lorencarvalho ! This is great and will work for us.
