### ISSUE TITLE
How can I print a message on first run?

### ISSUE THREAD

**Issue by mhucka** [linkedin/shiv#184]
In experiment with shiv for a project of mine, it works great, but the first time you run the application built, it takes an extra long time (presumably because shiv is unpacking stuff the first time it's run). Is there a way to make it print a message upon first execution? Then I could arrange to print a message along the lines of "Doing some first-time stuff -- please be patient".

**Comment by mhucka** [comment]
On further reading, it appears that `--preamble` might be the way to do this. I'll experiment with that.

**Comment by lorencarvalho** [comment]
hi @mhucka, unfortunately, since the preamble is packaged inside the zipapp (with the rest of the dependencies) it must be extracted _before_ it's invoked, so the preamble execution happens after the pyz extracts itself.

Also, there's unfortunately no existing feature that can accomplish what you are looking for. Normally I like to use things like [halo](http://halo.josealerma.com/index.html) for giving the user some feedback about what's going on (and why they have to wait), so I feel your pain here.
