### ISSUE TITLE
Can't use generated executable file under a machine with more than 64 threads

### ISSUE THREAD

**Issue by nbahar-intel** [linkedin/shiv#200]
Hi,
I'm having issues invoking the executable file generated by shiv with a machine (windows server) with more than 64 threads.

I'm guessing shiv (or the python interpreter) extracting the executable file upon first execute with subprocessing in parallel. But, when used with a machine with more than 64 threads it generates an error:

`ValueError: need at most 63 handles, got a sequence of length 63`
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/81356627/143223966-a4890f76-0c66-4ec1-95ed-ea986f46b32f.png)

Any workarounds ?

**Comment by lorencarvalho** [comment]
Hi @nbahar-intel, 

I don't have a Windows machine handy to test with at the moment, but I am pretty stumped by this because `shiv` does not use `multiprocessing` at all. Originally I thought that there may be a bug causing the `--compile-pyc` flag to default to `True` somehow/somewhere, but I made sure that it is (correctly) defaulting to `False`, that's the only place where `multiprocessing` would even come into play ([here](https://github.com/linkedin/shiv/blob/main/src/shiv/bootstrap/__init__.py#L142-L143)).

I even checked the standard library [zipfile module](https://github.com/python/cpython/blob/f6648e229edf07a1e4897244d7d34989dd9ea647/Lib/zipfile.py#L1651-L1691) to make sure it wasn't making calls to multiprocessing. 😕 

I'll see what I can do about getting my hands on a Windows machine to try and reproduce this.

**Comment by nbahar-intel** [comment]
@lorencarvalho It seems like not using `--compile-pyc` flag does infect solve the issue when executing the generated file.

**Comment by lorencarvalho** [comment]
@nbahar-intel oh! I didn't realize you were using that flag. Yeah, disabling that should be an effective way to avoid this issue. If you still want to pre-compile `pyc` files, you can leave the setting on, but make sure that you set the environment variable `SHIV_COMPILE_WORKERS` to a sane value (like 1, which disables the use of `multiprocessing`). By default we invoke `compileall.compile_dir` with `workers=0` which is shorthand for using `os.cpu_count` to determine the number of workers. [Per the documentation](https://docs.python.org/3/library/compileall.html#cmdoption-compileall-j).
