### ISSUE TITLE
Supporting Python 3.5

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [linkedin/shiv#211]
Greetins,

Is there any major blocker for not supporting Python 3.5?

**Comment by Abdur-rahmaanJ** [comment]
Here is a [demo](https://github.com/Abdur-rahmaanJ/shiv/tree/main/src/shiv_3.5) with all issues ironed out but i still get errors as to the package  target does not exist `ImportError: No module named <package name>`

**Comment by lorencarvalho** [comment]
Hi @Abdur-rahmaanJ,

My only motivation for excluding 3.5 support was that I wanted to use the type hint syntax introduced in 3.6, I'm actually considering dropping support for 3.6 as well now given that it's been almost 5 months since it reached EOL.

For those reasons, I don't anticipate we will be supporting 3.5 in the future.
