### ISSUE TITLE
Rename shiv to something else

### ISSUE THREAD

**Issue by xifumi** [linkedin/shiv#39]
https://en.wikipedia.org/wiki/Shiv

Not to mention that there are folks who go by the name `shiv`

**Comment by sixninetynine** [comment]
Hi, thanks for opening an issue, but I’m not sure I follow, can you elaborate on this request?

**Comment by xifumi** [comment]
Shiv is a common proper noun. It's a personal nitpick but I prefer not to have open source projects that use my name on it. I was wonder if you all are open to renaming it to something that's not someone's name.

**Comment by sixninetynine** [comment]
The tool is technically named as an abbreviation of the (ever so slightly) longer "shiver" (which is mentioned in the announcement [blog post](https://engineering.linkedin.com/blog/2018/05/introducing-and-open-sourcing-shiv)), certainly not meant as a proper noun. 

It sort of evolved from that into the shorter version because I found myself typing `shiv *tab*` in my terminal window and eventually just shortened the name. 

I'm sorry if this is an annoyance! I would be happy to add an additional entry into the console_scripts dict with the long name, but I feel it's a bit late to change the name altogether 😕

**Comment by xifumi** [comment]
Fair enough. Thanks for your consideration. Feel free to close this issue.
