### ISSUE TITLE
Windows compatibility?

### ISSUE THREAD

**Issue by scphantm** [linkedin/shiv#45]
I am trying to make python a first class language in my enterprise.  Problem is we do development on windows and deploys to linux.  

The thing that has prevented us from beginning to write stuff in python before was Pex was never windows compatible (because it relied on symlinks).  Is shiv?

**Comment by anthrotype** [comment]
I just tried to run shiv on Windows python3.7 and it seems to be working. I had to name the output file with .pyz extension for python zip-apps, which is associated with the installed python by default, and then it runs normally from the cmd.exe.

I tried running the test suite locally and I see 5 failures.

I'll try to work on an appveyor.yml setup for the shiv repo and address the windows test failures.

**Comment by sixninetynine** [comment]
thanks @anthrotype !

full windows support is definitely something we want, I simply don't have ready access to a windows machine to test with.

@scphantm iirc we don't use symlinks anywhere, so there's nothing that ought to be explicitly incompatible with windows. Doing development on windows and then deploying to linux could be problematic since the `pyz` files we produce are not cross-compatible, but if you build for each target it should be be totally fine

**Comment by sixninetynine** [comment]
@scphantm we are now testing on windows thanks to @anthrotype & #46, so you ought to be good to go. If you run into any issues please let us know!

**Comment by sixninetynine** [comment]
@anthrotype good call, I added a blurb
