### ISSUE TITLE
Modules in the zipapp aren't visible from subprocesses

### ISSUE THREAD

**Issue by pfmoore** [linkedin/shiv#74]
This may not be easy to solve - and indeed, it may be that all that needs to be done is document this as an unsupported use case - but it prevents the virtual environment manager `pew` being bundled as a zipapp with shiv.

The only possible way of addressing this would be by putting shiv's `site-packages` into the `PYTHONPATH` environment variable for subprocesses, But that might have its own issues - I haven't thought the implications through.

Simple test case to reproduce the issue:

```
>shiv -o ex.pyz -e main:main --site-packages x virtualenv
 shiv! 🔪
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/b6/30/96a02b2287098b23b875bc8c2f58071c35d2efe84f747b64d523721dc2b5/virtualenv-16.0.0-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-16.0.0
 done
>py .\ex.pyz
C:\[...]\Python37\python.exe: No module named virtualenv
Traceback (most recent call last):
  File "C:\[...]\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\[...]\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".\ex.pyz\__main__.py", line 3, in <module>
  File ".\ex.pyz\_bootstrap\__init__.py", line 125, in bootstrap
  File "C:\[...]\.shiv\ex_8792863b-a069-46b2-ac25-7d2750b38a7b\site-packages\main.py", line 5, in main
    subprocess.check_call([sys.executable, '-m', 'virtualenv', '--help'])
  File "C:\[...]\Python37\lib\subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\[...]\\Python37\\python.exe', '-m', 'virtualenv', '--help']' returned non-zero exit status 1.
```

**Comment by sixninetynine** [comment]
hi @pfmoore,

yeah, this is currently an unsolved problem with many possible approaches. 

my personal approach to this problem is to build a pyz _without_ an entrypoint, and then use that pyz as the "interpreter". This works thanks to the fallback on `code.interact`. However this assumes some familiarity with the code _making_ the subprocess calls. For third party stuff you simply want an executable of (such as `pew`), you obviously don't have that luxury 😞 .

I've toyed with the idea of including a build-time argument that would instruct shiv to append to PYTHONPATH, but, like you, I haven't really thought through potential pitfalls there.

**Comment by sixninetynine** [comment]
There's a bit of similar discussion in https://github.com/linkedin/shiv/issues/40

**Comment by pfmoore** [comment]
Thanks, I hadn't found that other issue, I'll read through the discussion there. As I have a particular use case in mind, I'll do some thinking and experimenting, and see what I can come up with. One likely issue is that it's not at all obvious that you always want the same behaviour (I can imagine sometimes wanting the subprocess call to see the modules in the zipapp, and sometimes not).
